---
kind: Service
apiVersion: v1
metadata:
  name: swptwitterloadbalancer
spec:
  selector:
    app: swptwitterpod
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 80
      # Port to forward to inside the pod
      targetPort: 3000
      # Port accessible outside cluster
      nodePort: 30001
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: swptwitterpod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: swptwitterpod
    spec:
      containers:
        - name: twitterapi
          image: dacharat/twitter_api
          ports:
            - containerPort: 3000